name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
    validations:
      required: true
  - type: input
    id: product
    attributes:
      label: Product
      placeholder: "e.g., VibeMCP, Attestix, IssueVista"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
    validations:
      required: false
